/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hmap

class A

fun main() {
    val map = Hmap()

    val key = Key<Int>(name = "count")
    val key2 = Key<String>(name = "string-key")

    map.put(key, 12)
    map.put(key2, "Hello")

    println(map.getOrNull(key))
    println(map.getOrNull(key2))
}