(lang dune 3.1)

(name async_io)

(generate_opam_files true)

(source
 (github anuragsoni/sandbox))

(authors "Anurag Soni")

(maintainers "Anurag Soni")

(license BSD-3-clause)

(package
 (name async_io)
 (depends ocaml dune poll mtime psq))
